name: "Despliegue de docusaurus en quantcdn"

on:
  push:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build docs
        run: yarn run build

      - name: Show generated outputs
        run: find build

      - name: Cache local revision file
        id: cache-quant-revisions
        uses: actions/cache@v3
        with:
          path: .quant-revision
          key: quant-revision

      - name: Deploy updates to QuantCDN
        uses: quantcdn/deploy-action@v2.0.0
        with:
          customer: "${{ secrets.QUANT_CUSTOMER }}"
          project: "${{ secrets.QUANT_PROJECT }}"
          token: "${{ secrets.QUANT_TOKEN }}"
          dir: build
          chunk-size: 20
          skip-purge: true
          enable-index-html: true
          revision-log: .quant-revision

      - name: Purge the QuantCDN cache
        uses: quantcdn/purge-action@v1.2.0
        with:
          customer: "${{ secrets.QUANT_CUSTOMER }}"
          project: "${{ secrets.QUANT_PROJECT }}"
          token: "${{ secrets.QUANT_TOKEN }}"
          url_pattern: "/*"
