name: "Despliegue de docusaurus en quantcdn"

on:
  push:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Comprobar dependencias en cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Instalar dependencias necesarias/faltantes
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Compilar la web
        run: yarn run build

      - name: Ficheros estaticos generados
        run: find build

      - name: Fichero de revision para cache local
        id: cache-quant-revisions
        uses: actions/cache@v3
        with:
          path: .quant-revision
          key: quant-revision

      - name: Desplegar la web en quantcdn
        uses: quantcdn/deploy-action@v2.0.0
        with:
          customer: "${{ secrets.QUANT_CUSTOMER }}"
          project: "${{ secrets.QUANT_PROJECT }}"
          token: "${{ secrets.QUANT_TOKEN }}"
          dir: build
          skip-unpublish: true

      - name: Purgar la cache de quantcdn
        uses: quantcdn/purge-action@v1.2.0
        with:
          customer: "${{ secrets.QUANT_CUSTOMER }}"
          project: "${{ secrets.QUANT_PROJECT }}"
          token: "${{ secrets.QUANT_TOKEN }}"
          url_pattern: "/*"
          
