name: Comprobación de PR para la rama main

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar si el pr es de la rama desarrollo hacia la main
        id: check
        run: |
          if [[ "${{ github.head_ref }}" != "desarrollo" ]]; then
            echo "message=No se permite hacer pr a la rama main" >> $GITHUB_ENV
          fi

      - name: Cerrar pull request y comentar motivo.
        if: env.message != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.message
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            });
