name: Check-PR-main

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar si el PR es de la rama desarrollo hacia la main y es abierto por el propietario
        id: check
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && ( "${{ github.event.pull_request.head.ref }}" != "desarrollo" || "${{ github.event.pull_request.user.login }}" != 'davidrgfoss' ) ]]; then
            echo "message=🌠🌠La rama main solo acepta pull request desde la rama desarrollo y del propietario o asociados🌌🌌" >> $GITHUB_ENV
          fi

      - name: Cerrar pull request y comentar motivo.
        if: env.message != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.message
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            });
