name: Scan Snyk

on:
  pull_request:
    branches: [ "desarrollo" ]
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Comprobar cache dependencias nodejs
        id: cache-node-modules
        uses: actions/cache@main
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Instalar las dependencias
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
        
      - name: Escanear en busca de vulnerabilidades con Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
